---
title: "Milestone 2"
author: "Amy Zhou"
date: "2/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

github repo: https://github.com/amyzhou9/MS_2

## First Selected Project 
### Housing Prices in Three Major US Cities by Sophia Zheng 
site link: https://szheng5.shinyapps.io/housing-explorations-app/

repository link:https://github.com/sophz55/housing-price-explorations

It was very cool to be able to see how prices changed in some of the
most expensive cities in the country over time. Zheng was able to break the graphs down into many different
measurement metrics  on the explore page from home value index to rent list prices. Each measure was able to give the new viewer a new outlook into the data. It however, may have been nice to have multiple graphs side to side so that the viewer can view the correlation between different metrics without flipping between graphs. The income and housing value comparisons graph was particularly interesting as it was animated
by year. It was really cool being able to visualise the dip in prices following the 2008 crisis. Unfortunately the maps by zipcode data does not seem to work. The data was reportedly already clean. All Zheng had to do was join some tables to generate different axis variables. Since the project only focuses on three cities, it is not necessarily a comprehensive representation of housing over the years. Having more 
smaller cities or cities in less affluent regions may underline other shifts. New York, San Francisco, and 
Seattle all have relatively stable economies since New York is New York and San Frnacisco and Seattle 
are two very tech based cities. Furthermore, there was not a lot of explanation of the data. Someone
with no experience with the housing market would likely be very confused when viewing the graphs. 

## Second Selected Project
### Catching Criminals: A Criminal Minds Analysis by Morgan Booker
site link: https://morganbooker.shinyapps.io/cm_analysis/

repository link: https://github.com/morganbooker/criminal_minds_analysis

I love the show Criminal Minds and have also wondered about how the show is structured specifically. This project required a significant amount of data gathering and manipulation. According to her third milestone,
the process she took was as follows: "First, I made a dataframe where each line in the script was a different row, then I wanted to be able to break each line up into a single word because I thought that might be helpful in filtering out the amount of times the word was said, so I found the tidytext package from Google, and used the unnest_tokens() function to achieve this. After doing this, I counted the amount of times a couple of key words from the show were said ("Unsub", "Reid", "Morgan" (two of the main characters))." Furthermore, according to her final project about page she also combined data from the wiki into her own dataframe. This is quite impressive. Her project is super thorough and has a lot of analysis. I like how many variables she addresses and her explanation ofthe data is super clear. The wordcloud was also super creative and I hope to maybe do something similar. Her criminal analysis tab further breaks down the data which I thought was super cool. The regression analysis was also super interesting if albeit not totally enlightening. Perhaps, a further analysis could be to see if the show is sexist or racist by seeing if female or males correlate more to catching a criminal. Over the aesthetics are pleasing. However, I must note that when first landing on the page, the nav bar is not totally obvious and I had to look for it (not sure if this is just me). 

